version: '3'

services:
  # db:
  #   image: bitnami/mongodb
  #   env_file:
  #     - .env
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    image: e-commerce/server
    env_file:
      - .env
    # depends_on:
    #   - db
    ports:
      - "8000:8000"
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/